baseURL = 'https://gecos-analytics.statichost.page/'
languageCode = 'en-us'
title = 'Gecos Analytics website'
theme = 'ananke'
sectionPagesMenu = 'main'

#[menus]
#  [[menus.main]]
#    name = 'Home'
#    url = '/'
#    weight = 10
#  [[menus.main]]
#    name = 'Products'
#    url = '/products'
#    weight = 20
#  [[menus.main]]
#    name = 'Posts'
#    url = '/posts'
#    weight = 30
